# Generated by Django 4.0 on 2026-08-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chome_app', '0003_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_bg',
            field=models.ImageField(blank=True, null=True, upload_to='profile_bg/'),
        ),
    ]
