# Generated by Django 4.0 on 2026-08-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chome_app', '0004_user_profile_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icon/'),
        ),
    ]
