# Generated by Django 4.0 on 2026-08-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chome_app', '0005_user_profile_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
