# Generated by Django 4.0 on 2026-08-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chome_app', '0006_user_profile_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='message_font',
            field=models.CharField(default='brush', max_length=20),
        ),
    ]
