# Generated by Django 4.0 on 2026-08-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chome_app', '0007_user_message_color_user_message_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
