# Generated by Django 4.0 on 2026-08-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chome_app', '0008_message_file_alter_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='created_at',
        ),
        migrations.AddField(
            model_name='schedule',
            name='color',
            field=models.CharField(default='#12b88e', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
